version: '3'
services:
  web:
    image: nginx
    volumes: 
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"  
      - "./docker/ssl:/etc/ssl"
      - "./src:/var/www/html"
      - "./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "userdb:/opt/userdb"
    ports:
      - "80:80"
      - "8443:443" 
    env_file:
      - ".env"
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - db
  php:
    image: "userdb_php:${PHP_TAG}"
    restart: always
    env_file:
      - "php.env"
      - ".env"

    volumes:
      - "userdb:/opt/userdb"
 #  phpmyadmin:
 #   image: phpmyadmin/phpmyadmin
 #   ports:
 #     - "8080:8080"
 #   links:
 #     - db
 #   environment:
 #     PMA_HOST: db
 #   depends_on:
 #     - db
  db:
    image: mariadb:10.1
    restart: always
    env_file:
      - ".env" 
    ports:
      - "3306:3306"
    command: --max_allowed_packet=32505856    
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
   
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:  
  userdb: 
